MySite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from .sitemap import BlogSitemap
from blog.models import Entry


info_dict = {
            'queryset' : Entry.objects.all(),
            'date_field' : 'modified',
        }

urlpatterns = [
    # Examples:
    # url(r'^$', 'MySite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'^$', include('blog.urls', namespace='blog')),

    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps' : {'blog' : GenericSitemap(info_dict, priority=0.5, changefreq="monthly")} },
        name='django.contrib.sitemaps.views.sitemap'
    ),
]

blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'MySite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.BlogIndex.as_view(), name="index"),
    url(r'^detail/(?P<slug>\S+)$', views.EntryDetail.as_view(), name="entry_detail"),
    url(r'^search/$', views.EntrySearch.as_view(), name="entry_search"),
    url(r'^about/$', views.About.as_view(), name="about"),
    url(r'^rss/$', views.LatestEntriesFeed(), name="rss"),
    url(r'^markdowntest/$', views.MarkdownTest.as_view(), name="markdowntest"),
]

blog/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title


class Entry(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/detail/%s" % self.slug

    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ['-created']

class Comment(models.Model):
    commenter = models.CharField(max_length=50)
    body = models.TextField()
    posted = models.DateTimeField(auto_now_add=True)
    entry = models.ForeignKey('Entry')

    def __str__(self):
        return self.commenter+" --" + self.entry.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from django import template

from django.contrib.syndication.views import Feed
from django.contrib import sitemaps

from blog.models import *

import re
import markdown

from itertools import chain, combinations, permutations

item_per_page = 5

def powerset(iterable):
    s = list(iterable)
    return chain.from_iterable(permutations(s,r) for r in range(len(s) + 1))

def getSubsetList(iterable):
    c = powerset(iterable)
    return [ list(x) for x in c]

def paginate(request, result_list,  per_page):
    paginator = Paginator(result_list, per_page)
    page = request.GET.get("page")
    results = []
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
            results = paginator.page(paginator.num_pages)
    return results

class BlogIndex(View):

    def get(self,request):
        context = {}
        entry_list = Entry.objects.all()
        context['entries'] = entry_list
        context['entries_paginated'] = paginate(request, entry_list,  item_per_page)
        return render(request, 'blog/index.html', context)

class EntryDetail(View):

    def get(self,request, slug):
        context = {}
        entry = get_object_or_404(Entry, slug=slug)
        comments = Comment.objects.filter(entry=entry)
        context['entry'] = entry
        context['comments'] = comments
        return render(request, 'blog/detail.html', context)

    def post(self, request, slug):
        entryid = request.POST.get('entryid')
        commenter = request.POST.get('commenter','')
        body = request.POST.get('body','').strip()
        if body:
            entry = get_object_or_404(Entry, id=entryid)
            comment = Comment(commenter=commenter, entry=entry, body=body)
            comment.save()
            return HttpResponseRedirect('/blog/detail/'+slug)

class EntrySearch(View):

    def get(self, request):
        context = {}
        querystring = request.GET.get('query','').strip()
        query = Q()
        if not querystring:
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            querystring = querystring.lower()
            # split according to spaces
            query_list = re.split(r'\s+', querystring)
            temp = [ re.escape(string) for string in query_list]
            query_list = list(set(temp))

            '''
            # get possible words
            words_combinations = getSubsetList(query_list)
            word_list = []
            for x in words_combinations:
                if len(x)>0:
                    word_list.append(' '.join(x))
            '''

            regexstring = r'(' + '|' .join(query_list) + ')'

            #print(query_list)

            entry_list = []
            '''
            for tagstr in query_list:
                tagobj= Tag.objects.filter(title=tagstr)
                if tagobj:
                    entryobj = Entry.objects.filter(tags = tagobj)
                    entry_list += entryobj

            entry_list = list(set(entry_list))
            entry_list = sorted(entry_list, key=lambda x: x.created, reverse=True)
            '''

            title_list= Entry.objects.filter(title__iregex=regexstring).distinct()
            tag_list= Entry.objects.filter(tags__title__iregex = regexstring).distinct()

            from itertools import chain
            entry_list = list(set(chain(title_list, tag_list)))
            entry_list = sorted(entry_list, key=lambda x: x.created, reverse=True)

            context['querystring'] = querystring
            context['query'] = querystring
            context['entries'] = entry_list
            context['entries_paginated'] = paginate(request, entry_list, item_per_page)
            context['title_list'] = title_list
            context['tag_list'] = tag_list
            return render(request, 'blog/searchresults.html', context) 

    def post(self, request):
        return HttpResponse("hello")

class About(View):

    def get(self, request):
        context = {}
        about_file = open("blog/markdownfiles/about.md", 'r')
        about_text = about_file.read()
        context['about'] = about_text
        about_file.close()
        return render(request, 'blog/about.html', context)

class LatestEntriesFeed(Feed):
    title = "CodingParadox blog post"
    link = "/blog/"
    description = "updates on latest blogs"
    feed_copyright = "Copyright @ Nishan Pantha"
    feed_url = "/blog/rss"

    def items(self):
        return Entry.objects.order_by('-created')[:5]

    def item_title(self, item):
        return item.title

    def item_pubdate(self, item):
        return item.created

    def item_description(self, item):
        return markdown.markdown(item.body, safe_mode='escape')

class MarkdownTest(View):

    def get(self, request):
        context = {}
        markdowntest_file = open("blog/markdownfiles/markdowntest.md", 'r')
        markdowntest_text = markdowntest_file.read()
        context['markdowntest'] = markdowntest_text
        markdowntest_file.close()
        return render(request, 'blog/markdowntest.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load markdowntags %}

{% block head %}
    <title>About</title>
{% endblock %}

{% block content %}
    <div class="card-panel blog-entry">
        <div class="row">
            <div class="col s12 flow-text center-align">
                {{ about|markdownify|safe}}
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
{% load encodeurl %}
{% load shuffle %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="description" content="">
    <meta name="author" content="">

    {% block head %}
    {% endblock %}

    <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="{% static 'css/materialize.min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/codehilite.css' %}" type="text/css" rel="stylesheet">
    <style>
        {% block style %} {% endblock %}
    </style>

</head>

<body>
    {# navbar when large --- sidebar when small (shrunken) #}
    <nav>
        <div class="nav-wrapper z-depth-1 red darken-2">
            
            <div class="row">

                {# mobile #}
                <div class="col s3" id="mobile">
                    <a href="#" data-activates="mobile-sidebar" class="button-collapse">
                        <i class="material-icons">reorder</i>
                    </a>

                    <ul class="side-nav collection" id="mobile-sidebar">
                        {#--- search box ---#}
                        <li class="collection-item">
                        <form method="GET" action="{% url 'blog:entry_search' %}">
                                <div class="row">
                                    <div class="col s2 m2">
                                        <i class="material-icons" id="mobile-submit" type="submit">search</i>
                                    </div>

                                    <div class="col s10 m10">
                                        <div class="input-field black-text">
                                            <input id="mobile-search" 
                                                style="height:35px; width:120px;" 
                                                type="text" 
                                                name="query" 
                                                placeholder="search" 
                                            required>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </li>
                        {#--- end search box ---#}

                        <li class="collection-item"><a href="{% url 'blog:index' %}"><b>HOME</b></a></li>
                        <li class="collection-item"><a href="#tagcloud" class=""><b>TAG CLOUD</b></a></li>
                        <li class="collection-item"><a href="#archives" class=""><b>ARCHIVES</b></a></li>
                        <li class="collection-item"><a href="{% url 'blog:rss' %}"><b>RSS</b></a></li>
                        <li class="collection-item"><a href="{% url 'blog:about' %}"><b>ABOUT</b></a></li>
                    </ul>
                </div>
                {#---mobile end-----#}

                {#---- normal ----- #}
                {# --- search box --- #}
                <div class="col s4 hide-on-med-and-down" id="desktop">
                    <form method="GET" action="{% url 'blog:entry_search' %}">
                        <div class="row">

                            <div class="col s1">
                                <button id="desktop-submit" class="mdi-action-search btn-floating btn-small waves-light red" type="submit" >
                                </button>
                            </div>
                            <div class="col s11">
                                <div class="input-field">
                                    <input id="desktop-search" type="text" placeholder="search" name="query" required>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
                {#--- end search box --- #}

                {#--- rest navbar ---#}
                <div class="col s8">
                    <a href="{% url 'blog:index' %}" class="brand-logo center">CodingParadox</a>

                    <ul class="right hide-on-med-and-down">
                        <li><a href="{% url 'blog:rss' %}">RSS</a></li>
                        <li><a href="{% url 'blog:about' %}">ABOUT</a></li>
                    </ul>
                </div>
                {#--- end rest of navbar ---#}
            {#------#}

            </div>
            
        </div>
    </nav>
    {# -------------------- #}

   
    {# main content #}
    <div class="" style="width:100%;">
    <br/>
    <br/>
    <div class="row">

        <!-- actual contents -->
        <div class="col s12 l10 container">
            {% block content %}
            {% endblock %}
        </div>
        <!-- end actual contents -->

        <!-- side bar -->
        <div class="col s12 l2 container">

            <!-- archives -->
            <div class="row">
                <div class="col s12 card" id="archives">
                    <h5 class="red-text text-darken-3 center"> Archives </h5>
                    {% regroup global_entries by created|date:"Y" as year_list %}

                    <!-- collapsible for year -->
                    <ul class="collapsible" data-collapsible="expandable">
                        {% for year in year_list %}
                            <li>
                                <div class="collapsible-header">{{year.grouper}}</div>
                                <div class="collapsible-body">

                                    {% regroup year.list by created|date:"F" as month_list %}

                                    <div class="row">
                                        <div class="col s12">
                                    
                                            <!-- create collapsible for every month -->
                                            <ul class="collapsible collection" data-collapsible="expandable">
                                                {% for month in month_list %}
                                                <li>
                                                <div class="collapsible-header">{{month.grouper}}</div>
                                                <div class="collapsible-body">
                                                {% for entry in month.list %}
                                                <div class="row">
                                                    <div class="col s12">
                                                    <a class="collection-item blue-text text-darken-2" 
                                                        href="{% url 'blog:entry_detail' slug=entry.slug  %}">
                                                        {{ entry }}
                                                    </a>
                                                    </div>
                                                </div>
                                                {% endfor %} {# endfor for entry loop #}
                                                </div>
                                                </li>
                                                {% endfor %} {#  endfor for month loop #}
                                            </ul>
                                            <!-- end month collapsible -->

                                        <div>
                                    </div>

                                </div>
                            </li>
                        {% endfor %} {# endfor for year loop #}
                    </ul>
                    <!-- end collapsible for year -->

                </div>
            </div>
            <!-- end archives -->

            <!-- tag cloud -->
            <div class="row">
                <div class="col s12 card" id="tagcloud">
                    <h5 class="red-text text-darken-3 center">Tag Cloud </h5>
                    <div class="divider"></div>
                    {% for tag,scale in tagcloud.items|shuffle %}
                        <a href=" {% url 'blog:entry_search' %}?query={{tag|encodeurl}}"
                            style="font-size: {{scale}}em"
                        >
                            {{tag}}
                        </a>
                        &nbsp;
                    {% endfor %}
                </div>
            </div>
            <!-- end tag cloud -->

        </div>
        <!-- end sidebar -->

    </div>
    <!-- end row -->


    <br/>
    </div>
    {# -------------------- #}

    <footer class="page-footer red darken-2">
        <div class="container">
            <div class="row center-align">
                <div class="col l6 s12">
                    <h5 class="white-text">Proudly developed using
                        <a target="_blank" href="https://www.djangoproject.com/" class="grey-text text-lighten-3">
                            <u>Django</u>
                        </a>
                    </h5>
                </div>

                <div class="col l4 offset-12 s12">
                    <h5 class="white-text">Contact</h5>
                    <ul>
                        <li>
                            <a class="grey-text text-lighten-3" target='_blank' 
                                href="http://twitter.com/nishPARADOX">
                                <img src = "{% static 'images/icons/twitter.png' %}" align="top" />
                                twitter(@nishPARADOX)
                            </a>
                        </li>

                        <li>
                        <a class="grey-text text-lighten-3" target='_blank' 
                            href="https://github.com/NISH1001">
                            <img src = "{% static 'images/icons/github.png' %}" align="top" />
                            github(NISH1001)
                        </a>
                        </li>

                    </ul>
                </div>
            </div>

            <div class="row">
                <div class="col s12 center-align">
                    <a class="grey-text text-lighten-3" href="#"><u>Back To Top</u></a>
                </div>
            </div>
        </div>

        <div class="footer-copyright center-align">
            © 2015 Copyright @ Nishan Pantha
        </div>
    </footer>

    {% block js %}
    {% endblock %}

    <script>
        $(document).ready(function()
        {
            $(".button-collapse").sideNav();
            $(".modal-trigger").leanModal();

            $('a[href*="#"]').click(function()
            {
                $($(this).attr("href")).effect("highlight", {color: '#ef9a9a'}, 4000);
            });
        });

        $('#desktop #desktop-submit').on('click', function()
        {
            if($('#desktop #desktop-search').val().trim()=='')
            {
                Materialize.toast("emtpy search", 250);
                return false;
            }
        });

        $('#mobile #mobile-submit').on('click', function()
        {
            if($('#mobile #mobile-search').val().trim()=='')
            {
                Materialize.toast("emtpy search", 250);
                return false;
            }
        });
    </script>
    <script src="{% static 'js/materialize.min.js' %}"></script>

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63014279-1', 'auto');
    ga('send', 'pageview');

    </script>

</body>

</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load markdowntags %}
{% load encodeurl %}

{% block head %}
    <title>{{entry}}</title>
{% endblock %}

{% block content %}

{# this is the main post element #}
<div class="card-panel collection">
    <a class="collection-item blue-text" href="{% url 'blog:entry_detail' slug=entry.slug %}"><h4>{{entry}} </h4> </a>
    
    <div class="collection-item"><p class="grey-text text-darken-1">Posted on : {{entry.created}}</p></div>
    
    <div class="collection-item">
        Tags : 
        {% for tag in entry.tags.all %}
            <a href=" {% url 'blog:entry_search' %}?query={{tag.title|encodeurl}}">{{tag}} </a> &nbsp;
        {% endfor %}
    </div>

    <div class="collection-item">
        <a href="https://twitter.com/share" class="twitter-share-button" data-via="nishparadox">Tweet</a>
    </div>

    <div class="collection-item blog-entry">
        <div class="flow-text"> {{ entry.body|markdownify|safe }} </div>
    </div>
</div>

{# main post end #}

{% comment %}
<div class="card-panel collection">
    <div class="collection-item"><h5 class="blue-text"> comments ({{ comments|length }}) </h5></div>

    {% if not comments %}
        <h5 class="grey-text text-darken-1">no comments for this post til now</h5>
    {% endif %}

    {% for comment in comments %}
        <ul class="collection">
            <li class="collection-item" style="padding-left: 10px;">
                <span class="grey-text text-darken-1">
                    <b> {{comment.commenter}} </b> said on {{ comment.posted }}
                </span>
                <div class="grey lighten-3">
                    <div class="blog-entry"> {{ comment.body|urlizetrunc:75|linebreaks }} </div>
            </div>
            </li>
        </ul>
    {% endfor %}
</div>

{# comment form #}
<div class="card-panel">
    <form action="{% url 'blog:entry_detail' slug=entry.slug %}" method="post" onsubmit="return validateComment()">
    {% csrf_token %}
        <input type="hidden" name="entryid" value="{{entry.id}}"/>
        
        <div class="input-field">
            <i class="mdi-action-account-circle prefix"></i>
            <label> Name </label>
            <input id="commenter" type="text" name="commenter" value="anonymous" />
        </div>

        <br/>

        <div class="input-field">
            <i class="mdi-editor-mode-edit prefix"></i>
            <textarea class="materialize-textarea" id="comment"  name="body"></textarea>
            <label for="comment">Comment</label>
        </div>

        <div class="center-align">
            <button class="btn-floating btn-large waves-effect waves-light red" type="submit" name="submit">
                <i class="mdi-content-add"></i>
                {# <i class="mdi-content-send-right"></i> #}
            </button>
        </div>
    </form>
</div>
{# -------------- comment-------------------------- #}
{% endcomment %}

{% endblock %}


{% block js %}

        {# tweet button #}
        <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
        </script>       

    <script>
        function validateComment()
        {
            commenter = document.getElementById('commenter').value;
            commenter = commenter.trim();
            body = document.getElementById('comment').value;
            body = body.trim();
            if(commenter.length <1 || body.length<1)
            {
                Materialize.toast("empty name/comment", 1000);
                return false;
            }
            else return true;
        }
    </script>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load markdowntags %}
{% load encodeurl %}

{% block head %}
    <title>CodingParadox</title>
{% endblock %}

{% block content %}

    {# entry list #}
    {% for entry in entries_paginated %}
    <div class="card-panel">
        <a href="{% url 'blog:entry_detail' slug=entry.slug  %}"><h4>{{entry}} </h4> </a>
        <span class="grey-text text-darken-1">Posted on : {{entry.created}}</span>
        <br/>
            Tags : 
            {% for tag in entry.tags.all %}
            <a href=" {% url 'blog:entry_search' %}?query={{tag.title|encodeurl}}">{{tag}} </a> &nbsp;
            {% endfor %}

        <div class="blog-entry grey lighten-4 flow-text" style="padding-left: 10px;">
            {{ entry.body|markdownify|safe|truncatechars_html:300 }}
        </div>

        <a href="{% url 'blog:entry_detail' slug=entry.slug  %}"><h5 class="blue-text text-lighten-2">Read More... </h5> </a>
    </div>
    {% endfor %}
    {#---------------#}

    {# pagination #}
    <div class="pagination">
        <div class="row center-align">

            <div class="col s12 m4">
                {% if entries_paginated.has_previous %}
                    <a href="?page={{ entries_paginated.previous_page_number }}" class="waves-effect waves-light btn-large red darken-2">newer</a>
                {% else %}
                    <a class="btn-large disabled">newer</a>
                {% endif %}

            </div>

            <div class="col s12 m4">
                <span class="teal-text text-darken-2">
                    page {{ entries_paginated.number }} of {{ entries_paginated.paginator.num_pages }}.
                </span>
            </div>

            <div class="col s12 m4">
                {% if entries_paginated.has_next %}
                    <a href="?page={{ entries_paginated.next_page_number }}" class="waves-effect waves-light btn-large red darken-2">older</a>
                {% else %}
                    <a class="btn-large disabled">older</a>
                {% endif %}
            </div>
        </div>

    </div>

    {# --------------- #}
{% endblock %}

blog/templates/blog/markdowntest.html
{% extends "blog/base.html" %}
{% load markdowntags %}

{% block content %}
    <div class="card-panel blog-entry">
        <div class="row">
            <div class="col s12 flow-text">
                {{ markdowntest|markdownify|safe}}
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/searchresults.html
{% extends "blog/base.html" %}
{% load markdowntags %}
{% load encodeurl %}

{% block content %}
    {% if not entries_paginated %}
        <div class="card grey lighten-5">
            <h5 class="center-align red-text text-darken-3">no results for Query: </h5>
            <h5 class="center-align blue-text text-darken-3">{{querystring}}</span></h5>
        </div>

        <div class="card-panel">
            <h4 class="center-align grey-text text-darken-1">NO POST AVAILABLE</span></h4>
        </div>
    
    {% else %}
    <div class="card grey lighten-5">
        <h5 class="center-align red-text text-darken-3">Search results for: </h5>
        <h5 class="center-align blue-text text-darken-3">{{query}}</span></h5>
        <h6 class="center-align red-text text-darken-3">Tags({{ tag_list|length }}) Title({{ title_list|length }})</h6>
    </div>
      
    <ul id="search">
        {# entry list #}
        {% for entry in entries_paginated %}
        <li>
        <div class="card-panel z-depth-2">
            <a href="{% url 'blog:entry_detail' slug=entry.slug  %}"><h4>{{entry}} </h4> </a>
            <span class="grey-text text-darken-1">Posted on : {{entry.created}}</span>
            <br/>
                tags : 
                {% for tag in entry.tags.all %}
                    <a href=" {% url 'blog:entry_search' %}?query={{tag.title|encodeurl}}">{{tag}} </a> &nbsp;
                {% endfor %}

            <div class="blog-entry grey lighten-4 flow-text" style="padding-left: 10px;">
                {{ entry.body|markdownify|safe|truncatechars_html:300 }}
            </div>

            <a href="{% url 'blog:entry_detail' slug=entry.slug  %}"><h5 class="blue-text text-lighten-2">Read More... </h5> </a>
        </div>
        </li>
        {% endfor %}
    </ul>

    {# pagination #}
    <div class="pagination">
        <div class="row center-align">

            <div class="col s12 m4">
                {% if entries_paginated.has_previous %}
                    <a href="?tag={{tag}}&amp;page={{ entries_paginated.previous_page_number }}" class="waves-effect waves-light btn-large red darken-2">previous</a>
                {% else %}
                    <a class="btn-large disabled">previous</a>
                {% endif %}

            </div>

            <div class="col s12 m4">
                <span class="teal-text text-darken-2">
                    page {{ entries_paginated.number }} of {{ entries_paginated.paginator.num_pages }}.
                </span>
            </div>

            <div class="col s12 m4">
                {% if entries_paginated.has_next %}
                    <a href="?tag={{tag}}&amp;page={{ entries_paginated.next_page_number }}" class="waves-effect waves-light btn-large red darken-2">next</a>
                {% else %}
                    <a class="btn-large disabled">next</a>
                {% endif %}
            </div>
        </div>

    </div>

    {# end pagination  --------------- #}

    {% endif %}
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function()
        {
            //for a transition effect
            //Materialize.showStaggeredList('#search')
        });
    </script>
{% endblock %}